services:
  automatekit-web-prod:
    image: ${DOCKER_USERNAME}/automatekit-web:prod-latest
    container_name: automatekit-web-prod
    restart: always
    ports:
      - "3000:80"

  automatekit-server-prod:
    image: ${DOCKER_USERNAME}/automatekit-server:prod-latest
    container_name: automatekit-server-prod
    restart: always
    ports:
      - "8000:8000"
    environment:
      NODE_ENV: production
      PORT: ${PROD_SERVER_PORT}
      DATABASE_URL: ${PROD_DATABASE_URL}
      ACCESS_SECRET: ${PROD_ACCESS_SECRET}
      REFRESH_SECRET: ${PROD_REFRESH_SECRET}
      APP_URL: ${PROD_APP_URL}
      GOOGLE_CLIENT_ID: ${PROD_GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${PROD_GOOGLE_CLIENT_SECRET}
      GOOGLE_REDIRECT_URI: ${PROD_GOOGLE_REDIRECT_URI}

  automatekit-executor-prod:
    image: ${DOCKER_USERNAME}/automatekit-executor:prod-latest
    container_name: automatekit-executor-prod
    restart: always
    environment:
      NODE_ENV: production
      DATABASE_URL: ${PROD_DATABASE_URL}
      REDIS_URL: ${PROD_REDIS_URL}
