services:
  automatekit-web-staging:
    image: ${DOCKER_USERNAME}/automatekit-web:staging-latest
    container_name: automatekit-web-staging
    restart: always
    ports:
      - "3100:80"

  automatekit-server-staging:
    image: ${DOCKER_USERNAME}/automatekit-server:staging-latest
    container_name: automatekit-server-staging
    restart: always
    ports:
      - "8100:8000"
    environment:
      NODE_ENV: production
      PORT: ${STAGING_SERVER_PORT}
      DATABASE_URL: ${STAGING_DATABASE_URL}
      ACCESS_SECRET: ${STAGING_ACCESS_SECRET}
      REFRESH_SECRET: ${STAGING_REFRESH_SECRET}
      APP_URL: ${STAGING_APP_URL}
      GOOGLE_CLIENT_ID: ${STAGING_GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${STAGING_GOOGLE_CLIENT_SECRET}
      GOOGLE_REDIRECT_URI: ${STAGING_GOOGLE_REDIRECT_URI}

  automatekit-executor-staging:
    image: ${DOCKER_USERNAME}/automatekit-executor:staging-latest
    container_name: automatekit-executor-staging
    restart: always
    environment:
      NODE_ENV: production
      DATABASE_URL: ${STAGING_DATABASE_URL}
      REDIS_URL: ${STAGING_REDIS_URL}
