FROM node:20-alpine AS builder

# install pnpm
RUN npm install -g pnpm

WORKDIR /app

ARG VITE_APP_BASE_URL
ARG VITE_API_BASE_URL
ENV VITE_APP_BASE_URL=${VITE_APP_BASE_URL}
ENV VITE_API_BASE_URL=${VITE_API_BASE_URL}

COPY pnpm-lock.yaml pnpm-workspace.yaml turbo.json package.json .npmrc ./

COPY apps/web ./apps/web
COPY packages ./packages

RUN pnpm install --frozen-lockfile

RUN pnpm turbo run build --filter=web

FROM nginx:alpine

COPY --from=builder /app/apps/web/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
