FROM node:22-alpine

WORKDIR /app

RUN npm install -g pnpm

COPY pnpm-lock.yaml pnpm-workspace.yaml turbo.json package.json ./
COPY packages ./packages
COPY apps/executor ./apps/executor

RUN pnpm install --frozen-lockfile

RUN pnpm turbo run build 

CMD [ "node", "./apps/executor/dist/index.js" ]