FROM node:20-alpine

# install pnpm
RUN npm install -g pnpm

WORKDIR /app

# copy workspace files
COPY pnpm-lock.yaml pnpm-workspace.yaml turbo.json package.json .npmrc ./

# copy backend source
COPY apps/server ./apps/server
COPY packages ./packages

# install dependencies
RUN pnpm install --frozen-lockfile

# build backend
RUN pnpm turbo run build --filter=server

WORKDIR /app/apps/server

EXPOSE 8000

CMD ["node", "dist/index.js"]