FROM node:20-alpine

# install pnpm
RUN npm install -g pnpm

WORKDIR /app

# copy workspace files
COPY pnpm-lock.yaml pnpm-workspace.yaml turbo.json package.json .npmrc ./

# copy backend source
COPY apps/executor ./apps/executor
COPY packages ./packages

# install dependencies
RUN pnpm install --frozen-lockfile

# build backend
RUN pnpm turbo run build --filter=executor

WORKDIR /app/apps/executor

CMD ["node", "dist/index.js"]