FROM node:22-alpine

WORKDIR /app

RUN npm install -g pnpm

COPY pnpm-lock.yaml pnpm-workspace.yaml turbo.json package.json ./
COPY packages ./packages
COPY apps/server ./apps/server

RUN pnpm install --frozen-lockfile

RUN pnpm turbo run build 

EXPOSE 8000

CMD [ "node", "./apps/server/dist/index.js" ]